import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Global from "./global";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "quang test app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">{children}</div>
        <Global />
      </body>
    </html>
  );
}
